apiVersion: v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: service-monitor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2024.9.9
    helm.sh/chart: minio-14.7.7
spec:
  selector:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  ports:
  - name: minio-api
    port: 9000
    targetPort: minio-api
  - name: minio-console
    port: 9001
    targetPort: minio-console
  type: ClusterIP

