apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: service-monitor    
spec:
  endpoints:
  - port: 9000
    scheme: http
    metrics_path: /minio/v2/metrics/cluster
  namespaceSelector:
    matchNames:
    - prod
  selector:
    matchLabels:
      app.kubernetes.io/instance: minio
